function createData(name, ingredients, price) {
    return { name, ingredients, price };
}

const rows = [
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
    createData('Margherita', 'pomodoro, mozzarella', 4),
    createData('Prosciutto', 'pomodoro, mozzarella, prosciutto cotto', 5),
    createData('Prosciutto e Funghi', 'pomodoro, mozzarella, prosciutto cotto, funghi porcini', 6),
];

export default rows;